# Generated by Django 5.2.13 on 2026-04-24 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_jti', models.CharField(max_length=255, unique=True, verbose_name='JTI refresh токена')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('device_name', models.CharField(default='Неизвестное устройство', max_length=120, verbose_name='Устройство')),
                ('browser_name', models.CharField(default='', max_length=60, verbose_name='Браузер')),
                ('os_name', models.CharField(default='', max_length=60, verbose_name='ОС')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('last_activity_at', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия пользователя',
                'verbose_name_plural': 'Сессии пользователей',
                'ordering': ['-last_activity_at'],
                'indexes': [models.Index(fields=['user', '-last_activity_at'], name='user_sessio_user_id_08e615_idx')],
            },
        ),
    ]
