# Generated by Django 6.0.2 on 2026-04-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0038_alter_moduleblock_can_be_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/module/video/thumbnails/', verbose_name='Превью'),
        ),
    ]
